/*
<javascriptresource>
<name>BT Historator Button 3</name>
<category>Brusherator</category>
<enableinfo>true</enableinfo>
</javascriptresource>
*/

eval("@JSXBIN@ES@2.0@MyBbyBnABMAbyBn0AIgBbyBn0ABJCnASzEjYiMjJjCBAEjzOiFjYjUjFjSjOjBjMiPjCjKjFjDjUCfRBFegajMjJjChaiQjMjVjHiQjMjVjHiFjYjUjFjSjOjBjMiPjCjKjFjDjUftnftABnzBjFDnbyBn0ACJEnAEjzFjBjMjFjSjUEfRBFehaiQjMjVjHiQjMjVjHhAjOjPjUhAjGjPjVjOjEhMhAjUjIjJjThAjXjPjOhHjUhAjXjPjSjLhAjJjOhAiQjIjPjUjPjTjIjPjQhAiDiDhShQhRhThAhahIffZFnAnJInASzFjGjOjBjNjFFBndCftJKnASzIjFjWjFjOjUiPjCjKGCEjzJiDiTiYiTiFjWjFjOjUHfntnftJLnABXzLjFjYjUjFjOjTjJjPjOiJjEIfVGfCneXjDjPjNhOjLjSjJjUjTjLjJjZhOjIjJjTjUjPjSjBjUjPjSfJMnABXzEjUjZjQjFJfVGfCnegajDjPjNhOjLjSjJjUjTjLjJjZhOjIjJjTjUjPjSjZiTjXjJjUjDjIfJNnABXzEjEjBjUjBKfVGfCVFfBnfJOnABXzFjTjDjPjQjFLfVGfCneLiBiQiQiMiJiDiBiUiJiPiOfJPnAEXzIjEjJjTjQjBjUjDjIMfVGfCnfADB40BiAF4B0AiAG4C0AiAADAzEjNjBjJjONAQBJRnAEjNfnf0DzAOByB")