/*
<javascriptresource>
<category>Brusherator</category>
<enableinfo>true</enableinfo>
</javascriptresource>
*/

eval("@JSXBIN@ES@2.0@MyBbyBn0AHJAnABjzEjDiUiJiEBfNyBnAMAbyBn0ABZBnAEXzOjDjIjBjSiJiEiUjPiUjZjQjFiJiECfjzDjBjQjQDfRBVzBjTEfAffABE40BhAB0AzAFCCnfJDnABjzEjTiUiJiEGfNyBnAMDbyBn0ABZEnAEXzQjTjUjSjJjOjHiJiEiUjPiUjZjQjFiJiEHfjDfRBVEfAffABE40BhAB0AFCFnfJGnASzFjEjFjTjDhRIyBEjzQiBjDjUjJjPjOiEjFjTjDjSjJjQjUjPjSJfntnftJHnASzEjSjFjGhRKyBEjzPiBjDjUjJjPjOiSjFjGjFjSjFjOjDjFLfntnftJInAEXzHjQjVjUiOjBjNjFMfVKfyBRCEjBfRBFeEiNjOhAhAffFeQiCjSjVjTjIjFjSjBjUjPjShAiQjMjVjTffJJnAEXzMjQjVjUiSjFjGjFjSjFjOjDjFNfVIfyBRCEjBfRBFeEjOjVjMjMffVKfyBffJKnAEjzNjFjYjFjDjVjUjFiBjDjUjJjPjOOfRDEjBfRBFeEjTjMjDjUffVIfyBXzCiOiPPfjzLiEjJjBjMjPjHiNjPjEjFjTQfffACK4B0AiAI40BiAACAFByB")